services:
  - type: web
    name: luca-line-bot
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    env: node
    region: oregon
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
